const { askGeminiForJson } = require('./llm/geminiJsonService');
const { analyzeCodeEvidence, buildCodeEvidencePrompt, buildEvidenceTraceText } = require('./evaluation/codeEvidenceService');
const {
  fallbackProposalEvaluation,
  fallbackMilestoneFeedback,
  fallbackSubmissionScore,
} = require('./evaluation/fallbackService');
const { clamp, toFiniteNumber, truncateText } = require('./utils/textUtils');

const evaluateProposal = async ({ ideaText, course }) => {
  const prompt = `You are an academic evaluator for course project proposals.
Evaluate proposal fit for the given course.

Return ONLY JSON with this exact schema:
{
  "relevance": number,
  "alignment": number,
  "feasibility": number,
  "technical_depth": number,
  "decision": "approved" | "rejected",
  "feedback": string
}

Scoring rules:
- each score in [0, 10]
- use one decimal precision if needed
- decision should be "approved" only when proposal is sufficiently relevant and aligned.

Course description:
${course.description}

Course curriculum:
${course.curriculum}

Learning objectives:
${course.learning_objectives}

Evaluation criteria:
${course.evaluation_criteria}

Student proposal:
${ideaText}`;

  const response = await askGeminiForJson(prompt, {
    fallbackFactory: () => fallbackProposalEvaluation({ ideaText, course }),
  });
  return {
    scores: {
      relevance: Number(clamp(response.relevance ?? 0, 0, 10).toFixed(1)),
      alignment: Number(clamp(response.alignment ?? 0, 0, 10).toFixed(1)),
      feasibility: Number(clamp(response.feasibility ?? 0, 0, 10).toFixed(1)),
      technical_depth: Number(clamp(response.technical_depth ?? 0, 0, 10).toFixed(1)),
    },
    decision: String(response.decision || 'rejected').toLowerCase() === 'approved' ? 'approved' : 'rejected',
    feedback: String(response.feedback || 'No feedback generated by LLM.'),
  };
};

const generateMilestoneFeedback = async ({ submission, previousSubmissions, project, course, codeSnippets = [] }) => {
  const codeEvidenceAnalysis = analyzeCodeEvidence({
    progressNotes: submission.progress_notes,
    codeSnippets,
  });

  const previousSummary = (previousSubmissions || [])
    .map((item, idx) => `${idx + 1}. ${item.milestone}: ${truncateText(item.progress_notes, 320)}`)
    .join('\n') || 'No previous submissions.';

  const prompt = `You are a mentoring assistant for a project-based LLM course.
Give milestone feedback that is actionable and specific.

Return ONLY JSON with this schema:
{
  "feedback": string
}

Feedback requirements:
- 1 short strengths paragraph
- 1 short risks/gaps paragraph
- 1 short next-steps paragraph
- include concrete technical recommendations

Course description:
${course.description}

Course curriculum:
${course.curriculum}

Learning objectives:
${course.learning_objectives}

Project title:
${project.title}

Project idea:
${project.idea_text}

Current milestone:
${submission.milestone}

Current progress notes:
${submission.progress_notes}

Claim-vs-code evidence diagnostics:
- claim terms extracted from notes: ${codeEvidenceAnalysis.claimTerms.join(', ') || 'none'}
- matched terms found in code: ${codeEvidenceAnalysis.matchedClaims.join(', ') || 'none'}
- claim match ratio: ${codeEvidenceAnalysis.summary.claim_match_ratio}

${buildCodeEvidencePrompt(codeEvidenceAnalysis)}

Previous submissions summary:
${previousSummary}`;

  const response = await askGeminiForJson(prompt, {
    fallbackFactory: () => fallbackMilestoneFeedback(),
  });
  return String(response.feedback || 'Milestone feedback could not be generated.');
};

const computeSubmissionScore = async ({ submission, project, course, previousEvaluations = [], isFinal, codeSnippets = [] }) => {
  const codeEvidenceAnalysis = analyzeCodeEvidence({
    progressNotes: submission.progress_notes,
    codeSnippets,
  });

  const evaluationHistory = (previousEvaluations || [])
    .map((item, idx) => `${idx + 1}. ${item.milestone} | score=${item.score} | feedback=${truncateText(item.feedback, 260)}`)
    .join('\n') || 'No previous graded submissions.';

  const prompt = `You are a strict academic grader.
Score this submission using the course evaluation criteria and project context.
Use sequential grading: compare this submission with previous graded submissions and mention improvements/regressions.
Code evidence MUST have higher weight than narrative text.
If claims in narrative are not reflected in attached code evidence, reduce consistency score.

Return ONLY JSON with this schema:
{
  "text_score": number,
  "code_score": number,
  "consistency_score": number,
  "score": number,
  "grade": "A" | "B" | "C" | "D" | "F",
  "feedback": string
}

Scoring rules:
- each score in [0, 100]
- you must reflect this weighting intent: text 20%, code 50%, consistency 30%
- grade bands: A >= 90, B >= 80, C >= 70, D >= 60, else F

Course evaluation criteria:
${course.evaluation_criteria}

Course learning objectives:
${course.learning_objectives}

Project title:
${project.title}

Project idea:
${project.idea_text}

Submission milestone:
${submission.milestone}

Submission text:
${submission.progress_notes}

Claim-vs-code evidence diagnostics:
- claim terms extracted from notes: ${codeEvidenceAnalysis.claimTerms.join(', ') || 'none'}
- matched terms found in code: ${codeEvidenceAnalysis.matchedClaims.join(', ') || 'none'}
- claim match ratio: ${codeEvidenceAnalysis.summary.claim_match_ratio}

${buildCodeEvidencePrompt(codeEvidenceAnalysis)}

Previous graded history:
${evaluationHistory}

Is final submission:
${isFinal ? 'YES' : 'NO'}`;

  const response = await askGeminiForJson(prompt, {
    maxAttempts: 3,
    maxOutputTokens: 2000,
    fallbackFactory: (err) => fallbackSubmissionScore({
      submission,
      isFinal,
      codeEvidenceAnalysis,
      lastError: err,
    }),
  });

  // When the fallback fires it already contains a fully-computed score/grade.
  // Re-running the weighted blend on top of a pre-computed fallback score would
  // deflate the result (0.25 * fallback_score instead of using it directly).
  // We detect this by checking whether the response came from the fallback
  // (fallback sets text_score/code_score/consistency_score directly) vs. the LLM
  // (LLM returns individual component fields that we must blend ourselves).
  const hasFinalScore = Number.isFinite(Number(response.score)) && Number(response.score) > 0;
  const hasComponents = [
    response.text_score,
    response.code_score,
    response.consistency_score,
  ].every((v) => Number.isFinite(Number(v)));

  const textScore = clamp(toFiniteNumber(response.text_score, 0), 0, 100);
  const codeScore = clamp(
    toFiniteNumber(response.code_score, codeEvidenceAnalysis.summary.code_evidence_score),
    0,
    100
  );
  const consistencyScore = clamp(
    toFiniteNumber(response.consistency_score, codeEvidenceAnalysis.summary.claim_match_score),
    0,
    100
  );

  let score;
  let weightedComponentScore;
  let llmOverallScore;

  if (!hasComponents && hasFinalScore) {
    // Fallback path: use the pre-computed score directly, only apply penalty.
    llmOverallScore = clamp(toFiniteNumber(response.score, 0), 0, 100);
    weightedComponentScore = llmOverallScore;
    const penalizedScore = llmOverallScore - codeEvidenceAnalysis.summary.penalty_points;
    score = Number(clamp(penalizedScore, 0, 100).toFixed(2));
  } else {
    // LLM path: blend component scores with the LLM's own overall score.
    llmOverallScore = clamp(toFiniteNumber(response.score, 0), 0, 100);
    weightedComponentScore = textScore * 0.2 + codeScore * 0.5 + consistencyScore * 0.3;
    const blendedScore = weightedComponentScore * 0.75 + llmOverallScore * 0.25;
    const penalizedScore = blendedScore - codeEvidenceAnalysis.summary.penalty_points;
    score = Number(clamp(penalizedScore, 0, 100).toFixed(2));
  }

  const normalizedGrade = String(response.grade || '').toUpperCase();
  const grade = ['A', 'B', 'C', 'D', 'F'].includes(normalizedGrade)
    ? normalizedGrade
    : (score >= 90 ? 'A' : score >= 80 ? 'B' : score >= 70 ? 'C' : score >= 60 ? 'D' : 'F');

  const evidenceTrace = buildEvidenceTraceText(codeEvidenceAnalysis);
  const feedbackSections = [
    String(response.feedback || 'Evaluation feedback could not be generated.'),
    evidenceTrace,
    `[Weighted Components] text=${textScore.toFixed(1)} code=${codeScore.toFixed(1)} consistency=${consistencyScore.toFixed(1)} final=${score.toFixed(2)}`,
  ].filter(Boolean);

  return {
    score,
    grade,
    feedback: feedbackSections.join('\n\n'),
    evidence: {
      text_score: Number(textScore.toFixed(2)),
      code_score: Number(codeScore.toFixed(2)),
      consistency_score: Number(consistencyScore.toFixed(2)),
      weighted_component_score: Number(weightedComponentScore.toFixed(2)),
      llm_overall_score: Number(llmOverallScore.toFixed(2)),
      penalty_points: codeEvidenceAnalysis.summary.penalty_points,
      claim_match_ratio: codeEvidenceAnalysis.summary.claim_match_ratio,
      files: codeEvidenceAnalysis.perFileEvidence,
    },
  };
};

module.exports = {
  evaluateProposal,
  generateMilestoneFeedback,
  computeSubmissionScore,
};
